Repository Montellese/mediaimporter.plex, pull requests merged in 2020-06, with the labels that each got.

#22 Add Portuguese (Brazil) Translation
  resources/language/resource.language.pt_br/strings.po
Labels: Type: Improvement

#21 added feature to tag all items with the id of the plex library
  plex/api.py
  plexapi/video.py
Labels: Component: Synchronization, Type: Improvement

#23 Add support for direct play
  changelog.txt
  lib/importer.py
  lib/settings.py
  plex/api.py
  plex/constants.py
  plex/provider_observer.py
  resources/language/English/strings.po
  resources/providersettings.xml
Labels: Component: Observation, Component: Playback, Component: Synchronization, Type: Feature
